FROM tensorflow/tensorflow:2.3.0-gpu

RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN apt-get -y install jq

COPY . /app

WORKDIR /app

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt